### ISSUE TITLE
Issues about "your_datafile.h5"

### ISSUE THREAD

**Issue by Programmefy** [adammj/ecg-sleep-staging#1]
Hello, dear authur, I have encountered an issue with my ECG signals data. Originally, it was stored in a .doc format as a matrix where the first column represents Time (seconds) and the second column represents Amplitude (mV). Recently, I converted this data into a .h5 format. However, Python reports that my ecg_data file is broken. What could be causing this issue? Also, could you please clarify what format your data is in?
   I would appreciate any insights or advice you could provide.

**Comment by adammj** [comment]
Sure thing! Since I want to make sure that any questions you have are answered for anyone, you'll have to let me know what the complete error message is. Also, the README has a full section on the **Data file description**. Please make sure that your `.h5` file contains all of the variables I listed.

**Comment by adammj** [comment]
@Programmefy Did you figure out the issue? If not, please provide the complete error message, so that I can help.

**Comment by adammj** [comment]
Closing because there's been no response.
