### ISSUE TITLE
H5 file is broken, and unsure why

### ISSUE THREAD

**Issue by dht7166** [adammj/ecg-sleep-staging#5]
Hi, I have this ecg data I would like to run some sleep staging using some ecg data I got. I followed the steps for 0.5Hz highpass and scaling (might be wrong due to inexperience with filtering, but at least the shape looks ok-ish). When running the CPU-only model with no demographic, I received the following error:

```
has argument
../../../example.h5
preparing...
using device:  cpu
create large temp variable on device
create datasets...
evaluation (validation or testing) set:
there are 1 files:
checking:   0%|                    | 0/1 [00:00<?, ?it/s]../../../example.h5 is broken
checking: 100%|████████████████████| 1/1 [00:00<00:00,  5.22it/s]
error during checking
```

Little bit unsure what this error might be. I believe my data has a `ecgs`, `demographics`, and `midnight_offset` and all should be in the correct shape. The h5 file is attached for your convenient.

[example.h5.zip](https://github.com/user-attachments/files/17819526/example.h5.zip)

**Comment by adammj** [comment]
Looks like the issue is `ValueError: median of ecgs should be ~0 (found: 0.11067764728977372)`. I updated the code to move the validation code outside of the try block, so that the error is visible.

**Comment by dht7166** [comment]
Thanks. Moving the error message outside helped me with debugging the issue.

I have some follow up questions:
- For pre-processing the ecg signal, is the intention to process the whole ecg signal or per 30s epoch? I am asking since the model apparently check the median and value clipping per epoch instead of the whole signal.
- How strict is the requirement for ECG placement? Seems like the data I have access to have different placement (RA and LL) compared to your requirement (RA and LA). 
- Would you be open to write Python code to process arbitrary ECG data into your required format? I am happy to make a contribution for this.

**Comment by adammj** [comment]
I'm glad to help; it's good to hear you got it working.

In response to your questions:

- The model is only checking the median of the entire signal (which is why I don't specify an axis, see `SleepSubject.check_ecg_variable(self, ecgs)`). Granted, even with the specified high-pass filter, the isoelectric line will occasionally (regularly?) deviate from 0. The only way around that would be to increase the high-pass filter's cutoff, but that will increasingly distort the ECG's waveform—and will not be what the model was trained on. So, I would say that it is fine for any given epoch to deviate from 0, as I'm certain it does in the data I trained and tested the model on. I could get the statistics here, to drive the point home. I specify that the median of the entire recording should be 0 because this is what the model was trained and tested on, and if the inputs violate this assumption, I can't make any claims about the network's performance.
- This question keeps coming up, as I've had others contact me directly asking about the Lead I requirement. So I think I'll need to add more documentation to the website and repository on this point. There are two things to keep in mind: 
  - The model was only trained and evaluated on Lead I, so it's only seen Lead I data, and the performance has only been verified for Lead I data.  In other words, I can make zero claims about the ability of the model to work on the "wrong" data.
  - There is no such thing as "converting" ECG data from one electrode pair to another. Since this also applies to your third question, I'll expand below.
- I don't know your background, so I'm writing this statement more generally. In my discussions with others, I've noticed some misunderstanding about ECG data. I think because each of the different possible electrode pairs look pretty similar to the untrained eye, there is the expectation that they are all basically recording the same data. This appears true because it's just measuring the potential across the heart across different arbitrary axes, right? But this is not at all correct. I can explain with a very simple example: if two voltages cancel each other out such that the voltage sum is now 0, there is literally no way to recover the two inputs. They could be 10 mV or 1,000 kV—we'd never know. This is what's happening with ECG data too. Between any two pairs of electrodes, you're getting a different "view" into the heart—and therefore different action potentials will cancel or add. And this is why cardiologists take 12-lead ECGs for the most important diagnostics. Furthermore, if we were just generating a static 3D model of a "typical" heart, maybe 1-3 "pictures" could work for some cool ML technique (like Gaussian splatting) to get a sense of what the rest of the heart is like. But ECG is the time-varying dynamics of the electrical properties of a unique heart, at a unique point in time (the dynamics can and do change over the course of seconds). **TL;DR:** Although I'd love to write code to "convert" one lead to another, it just isn't even theoretically possible for a unique heart at a unique point in time, which is necessary to score sleep for a unique individual at a unique point in time.

However, on that last point, I do promise I'll get the pipeline converted from MATLAB to Python. 

As I said, I'll get some statistics on the epoch-wise median and also add more explanation about the ECG lead to the website and README.

Let me know if that clarifies or raises more questions for you.

**Comment by dht7166** [comment]
Thanks for the clarification. I do not have a background with ECG data so this helped.

**Comment by adammj** [comment]
For you or anyone that checks this closed issue, I added more details on the ECG Lead I requirements on the website:
https://cardiosomnography.com/requirements/#ecg-lead

I also added a figure at the end of the same page showing the median offsets of recordings versus individual epochs (of the data that was used to train and test the model).
